import { ChatOpenAI } from "@langchain/openai";
import { OpenAIEmbeddings } from "@langchain/openai";
import initAgent from "./agent";
import { initGraph } from "../graph";
import { sleep } from "@/utils";

{
  /*The function will:
1. Accept the user input as a string along with a Session ID generated by the framework}
2. Use any conversation history to rephrase the input into a standalone question
3. Pass the rephrased question to the Agent that will be responsible 
for selecting the correct tool and generating a response to satisfy the request 

*/
}
// tag::call[]
export async function call(input: string, sessionId: string): Promise<string> {
  // TODO: Replace this code with an agent
  await sleep(2000);
  return input;
}
// end::call[]
